services:
  backend:
    build: 
      context: backend
      dockerfile: dockerfile
    ports:
      - "80:80"
  frontend:
    build: 
      context: frontend
      dockerfile: dockerfile
    ports:
      - "8501:8501"