services:
  backend:
    build: backend/
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - mongo
    links:
    - mongo:db
  frontend:
    build: frontend/
    ports:
      - "80:8501"
  mongo:
    image: mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
